version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      
    image: spd-server
    container_name: spd-node-server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5002:5002"
    env_file: ./backend/.env
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: spd-client
    container_name: spd-react-client
    command: npm start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local